"""OpenAI Agents SDK adapter: InputGuardrail for munio verification.

Wraps munio Guard as an OpenAI Agents SDK ``InputGuardrail``.
When a tool call violates constraints, the guardrail triggers a tripwire
which raises ``InputGuardrailTripwireTriggered`` in the SDK.

Requires: ``pip install "munio[openai-agents]"`` (openai-agents>=0.1).

Usage::

    from munio import Guard
    from munio.adapters import create_guardrail

    guard = Guard(constraints="generic")
    agent = Agent(
        name="my_agent",
        guardrails=[create_guardrail(guard)],
    )
"""

from __future__ import annotations

import json
import logging
from typing import TYPE_CHECKING, Any

from munio.models import Action

if TYPE_CHECKING:
    from munio.guard import Guard

__all__ = ["create_guardrail"]

logger = logging.getLogger(__name__)

try:
    from agents.guardrails import (  # type: ignore[import-not-found]
        GuardrailFunctionOutput,
        InputGuardrail,
    )
except ImportError as _exc:
    raise ImportError(
        "OpenAI Agents SDK adapter requires openai-agents. "
        "Install with: pip install 'munio[openai-agents]'"
    ) from _exc


def create_guardrail(
    guard: Guard,
    *,
    name: str = "munio",
) -> InputGuardrail:
    """Create an OpenAI Agents SDK input guardrail powered by munio.

    The guardrail inspects the agent input for tool call information.
    If any tool call violates constraints, ``tripwire_triggered`` is set to
    ``True``, which causes the SDK to raise ``InputGuardrailTripwireTriggered``.

    On unexpected errors, the guardrail is **fail-closed**: it sets
    ``tripwire_triggered=True`` to block execution.

    .. note::
        ``InputGuardrail`` runs on the agent's *input*, not on tool calls
        generated by the agent. It works best in multi-agent pipelines where
        one agent's output (containing tool calls) is passed as input to
        another, or when tool call information is explicitly included in
        the input data (dict with ``tool``/``args`` or list of
        ``function_call`` items).

    Args:
        guard: A configured :class:`~munio.guard.Guard` instance.
        name: Guardrail name (shown in SDK logs/errors).

    Returns:
        An ``InputGuardrail`` instance ready for ``Agent(guardrails=[...])``.
    """

    async def _guardrail_fn(
        context: Any,
        agent: Any,
        input_data: Any,
    ) -> GuardrailFunctionOutput:
        try:
            # Try to extract tool calls from input_data
            tool_calls = _extract_tool_calls(input_data)

            if not tool_calls:
                # No tool calls found — nothing to verify
                return GuardrailFunctionOutput(
                    output_info={"checked": 0},
                    tripwire_triggered=False,
                )

            all_violations: list[dict[str, str]] = []
            for tool_name, tool_args in tool_calls:
                action = Action(tool=tool_name, args=tool_args)
                result = await guard.acheck(action)
                if not result.allowed:
                    all_violations.extend(
                        {
                            "tool": tool_name,
                            "constraint": v.constraint_name,
                            "message": v.message,
                        }
                        for v in result.violations
                    )

            if all_violations:
                logger.warning(
                    "munio guardrail triggered: %d violation(s)",
                    len(all_violations),
                )
                return GuardrailFunctionOutput(
                    output_info={"violations": all_violations},
                    tripwire_triggered=True,
                )

            return GuardrailFunctionOutput(
                output_info={"checked": len(tool_calls)},
                tripwire_triggered=False,
            )

        except Exception:
            logger.warning(
                "munio guardrail error (fail-closed, blocking)",
                exc_info=True,
            )
            return GuardrailFunctionOutput(
                output_info={"error": "guardrail_error"},
                tripwire_triggered=True,
            )

    return InputGuardrail(guardrail_function=_guardrail_fn, name=name)


def _extract_tool_calls(input_data: Any) -> list[tuple[str, dict[str, Any]]]:
    """Extract (tool_name, args) pairs from agent input data.

    Handles multiple input formats:
    - str: no tool calls
    - list of dicts with 'type'='function_call': OpenAI function call format
    - dict with 'tool' and 'args': direct Action-like format
    """
    calls: list[tuple[str, dict[str, Any]]] = []

    if isinstance(input_data, str):
        return calls

    if (
        isinstance(input_data, dict)
        and "tool" in input_data
        and isinstance(input_data.get("tool"), str)
    ):
        args = input_data.get("args", {})
        if isinstance(args, str):
            try:
                args = json.loads(args)
            except (json.JSONDecodeError, TypeError):
                # Fail-closed: include the tool call with empty args so the
                # Guard still evaluates it (allowlist checks will block).
                calls.append((input_data["tool"], {}))
                return calls
        if isinstance(args, dict):
            calls.append((input_data["tool"], args))
        return calls

    if isinstance(input_data, list):
        for item in input_data:
            if not isinstance(item, dict):
                continue
            # OpenAI function_call format
            if item.get("type") == "function_call":
                fn_name = item.get("name", "")
                fn_args = item.get("arguments", {})
                if isinstance(fn_args, str):
                    try:
                        fn_args = json.loads(fn_args)
                    except (json.JSONDecodeError, TypeError):
                        # Fail-closed: include with empty args so Guard evaluates.
                        if isinstance(fn_name, str) and fn_name:
                            calls.append((fn_name, {}))
                        continue
                if isinstance(fn_name, str) and fn_name and isinstance(fn_args, dict):
                    calls.append((fn_name, fn_args))

    return calls
